version: '3.9'

networks:
  corp-net:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

services:
  redis:
    image: redis:7-alpine
    container_name: corp-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - corp-net
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: corp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - corp-net
    ports:
      - "5432:5432"
