'use client';
import { useEffect, useState } from 'react';
import { useAppState } from '@/lib/use-app-state';
import { addThought } from '@/lib/storage';
export function VoiceCapture(){ const { state, setState } = useAppState(); const [text,setText]=useState(''); const [listening,setListening]=useState(false); const [supports,setSupports]=useState(false);
 useEffect(()=>{ setSupports(typeof window !== 'undefined' && ('webkitSpeechRecognition' in window || 'SpeechRecognition' in window)); }, []);
 const submit=(value:string, source:'voice'|'text')=>{ if(!value.trim()) return; setState(addThought(state, value, source)); setText(''); };
 const start=()=>{ const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if(!SR){alert('Speech API not supported'); return;} const rec = new SR(); rec.lang='ru-RU'; rec.interimResults=true; rec.continuous=false; rec.onresult=(e:any)=> setText(Array.from(e.results).map((r:any)=>r[0].transcript).join('')); rec.onend=()=>setListening(false); setListening(true); rec.start(); };
 return <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex min-h-[440px] flex-col justify-between gap-4"><button className="flex-1 rounded-[2rem] bg-emerald-600 text-2xl font-semibold shadow-lg active:scale-[0.99]" style={{minHeight:'40vh'}} onClick={start}>{listening ? 'Слушаю…' : 'Нажми и говори'}</button><textarea className="min-h-28 rounded-2xl border border-slate-700 bg-slate-950 p-4" value={text} onChange={e=>setText(e.target.value)} placeholder="Или напиши мысль"/><div className="flex gap-3"><button className="flex-1 rounded-2xl bg-slate-100 px-4 py-3 font-medium text-slate-950" onClick={()=>submit(text,'text')}>Отправить в инбокс</button><button className="rounded-2xl border border-slate-700 px-4 py-3 text-slate-200" onClick={()=>{setText(''); setListening(false);}}>Сброс</button></div><p className="text-sm text-slate-400">{supports ? 'Web Speech API доступен' : 'Голосовой ввод недоступен в этом браузере'}</p></div></section>}
